name: native image release

on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # 'ubuntu-latest', 'windows-latest', 'macos-latest'
        os: ['windows-latest']
    name: build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for GraalVM JDK 17
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.0'
        java-version: '17'
        components: 'native-image'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        gu --version
        native-image --version
        mvn clean native:compile -Pnative --file pom.xml --no-transfer-progress package
    # 压缩文件
    - name: Archive zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'target/json-sort-*'
        filename: json-sort-${{ matrix.os }}.zip
        exclusions: 'target/json-sort-*.txt'
    # 上传构建产物
    - name: Upload artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: json-sort-${{ matrix.os }}.zip
        path: json-sort-${{ matrix.os }}.zip
    # GitHub 上创建 release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: json-sort-${{ matrix.os }}.zip
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}